SeldonIO/MLServer

mlserver/grpc/dataplane_pb2.py, mlserver/grpc/dataplane_pb2_grpc.py, proto/dataplane.proto
- Rename `proto` package to `inference` to align with [Triton's](https://github.com/triton-inference-server/server/blob/0e67dd1c168bd056b4b56ec851ed6a600fd5fe02/src/core/grpc_service.proto#L29)
=> Rename proto package to align with Triton

mlserver/cli/serve.py, mlserver/settings.py, tests/cli/test_serve.py
On some scenarios (i.e. MMS servers), it makes sense to disable loading models at startup time. This PR adds an option to the server settings to do that.
=> Add option to disable loading models at startup

docs/examples/mlflow/README.ipynb, docs/examples/mlflow/README.md, runtimes/mlflow/mlserver_mlflow/runtime.py, runtimes/mlflow/tests/rest/conftest.py, runtimes/mlflow/tests/rest/test_invocations.py
Fixes #168 
- Add a custom handler to the MLflow runtime which mimics MLflow's `/invocations` endpoint
- Update MLflow example to showcase support for MLflow's scoring protocol
=> Add support for existing MLflow protocol

requirements/dev.txt
Reverts SeldonIO/MLServer#295
Downgrade black due to an incompatibility with `tensorflow` caused by tensorflow/tensorflow#51743
=> Revert "Bump black from 21.7b0 to 21.8b0"

requirements/dev.txt, runtimes/alibi-explain/requirements-dev.txt
- Lock `prance` to an older version to avoid strange `six` clash with latest version of `pip`. For more information, please check https://github.com/pypa/pip/issues/9613.
=> Add workaround for pip issues in CI

mlserver/repository.py, mlserver/settings.py, mlserver/utils.py, tests/conftest.py, tests/test_repository.py, tests/test_utils.py
Fixes #325 
- Add private `_source` field to `ModelSettings` and tweak `ModelRepository` to store there the original file path of the `model-settings.json` file (if any).
- Tweak the `get_model_uri` utility method to base the model's URI on the location of the `model-settings.json` file.
=> Make model URI in model-settings.json relative to the config file

.gitignore, Dockerfile, docs/conf.py, mlserver/version.py, runtimes/alibi-detect/mlserver_alibi_detect/version.py, runtimes/alibi-explain/mlserver_alibi_explain/alibi_dependency_reference.py, runtimes/alibi-explain/mlserver_alibi_explain/common.py, runtimes/alibi-explain/mlserver_alibi_explain/explainers/black_box_runtime.py, runtimes/alibi-explain/mlserver_alibi_explain/version.py, runtimes/alibi-explain/setup.py, runtimes/alibi-explain/tests/conftest.py, runtimes/alibi-explain/tests/helpers/tf_model.py, runtimes/alibi-explain/tests/test_black_box.py, runtimes/alibi-explain/tests/test_utils.py, runtimes/lightgbm/mlserver_lightgbm/version.py, runtimes/mlflow/mlserver_mlflow/version.py, runtimes/mllib/mlserver_mllib/version.py, runtimes/sklearn/mlserver_sklearn/version.py, runtimes/xgboost/mlserver_xgboost/version.py
Fetch metadata from v2 endpoint inference model and use the info to construct the internal inference request from alibi explain model.
Also in this pr:
- upgrade to alibi 0.6.2
- bump mlserver version to 0.6.0.dev4
- add KernelShap explainer
=> Sherif akoush/quickfix/get names from metadata endpoint

runtimes/alibi-explain/requirements-dev.txt
It seems that `nest_asyncio==1.5.2` makes the tests fail with the following error (see https://github.com/erdewit/nest_asyncio/issues/62 for more details):
```
runtimes/alibi-explain/tests/conftest.py:29: in <module>
nest_asyncio.apply()
../../.virtualenvs/mlserver-37/lib/python3.7/site-packages/nest_asyncio.py:14: in apply
raise ValueError('Can\'t patch loop of type %s' % type(loop))
E   ValueError: Can't patch loop of type <class 'NoneType'>
```
With `nest_asyncio==1.5.1`, tests still seem to pass, so pinning it for now until we find out more about it.
=> Pin nest_asyncio to 1.5.1

docs/conf.py, mlserver/version.py, runtimes/alibi-detect/mlserver_alibi_detect/version.py, runtimes/alibi-explain/mlserver_alibi_explain/explainers/black_box_runtime.py, runtimes/alibi-explain/mlserver_alibi_explain/runtime.py, runtimes/alibi-explain/mlserver_alibi_explain/version.py, runtimes/alibi-explain/setup.py, runtimes/alibi-explain/tests/conftest.py, runtimes/alibi-explain/tests/test_alibi_runtime_base.py, runtimes/alibi-explain/tests/test_black_box.py, runtimes/lightgbm/mlserver_lightgbm/version.py, runtimes/mlflow/mlserver_mlflow/version.py, runtimes/mllib/mlserver_mllib/version.py, runtimes/sklearn/mlserver_sklearn/version.py, runtimes/xgboost/mlserver_xgboost/version.py
add a custom endpoint `/explain` for alibi runtime for backward compatibility with legacy downstream users.
=> Sherif akoush/quickfix/explainer output

mlserver/codecs/base64.py, mlserver/codecs/datetime.py, mlserver/codecs/numpy.py, mlserver/codecs/pack.py, mlserver/codecs/pandas.py, mlserver/codecs/string.py, mlserver/errors.py, mlserver/rest/responses.py, runtimes/alibi-detect/mlserver_alibi_detect/protocols/request_handler.py, runtimes/alibi-detect/mlserver_alibi_detect/protocols/seldon_http.py, runtimes/alibi-detect/mlserver_alibi_detect/protocols/tensorflow_http.py, runtimes/alibi-detect/mlserver_alibi_detect/protocols/v2.py, runtimes/alibi-explain/mlserver_alibi_explain/common.py, runtimes/alibi-explain/mlserver_alibi_explain/errors.py, runtimes/alibi-explain/mlserver_alibi_explain/runtime.py, runtimes/alibi-explain/tests/test_alibi_runtime_base.py, runtimes/alibi-explain/tests/test_black_box.py, runtimes/alibi-explain/tests/test_common.py, tests/codecs/test_base64.py, tests/codecs/test_datetime.py, tests/codecs/test_middleware.py, tests/codecs/test_numpy.py, tests/codecs/test_pandas.py, tests/codecs/test_string.py, tests/grpc/test_codecs.py, tests/grpc/test_converters.py, tests/rest/test_codecs.py
Fixes #400
- Change current codec logic so that `BYTES` payloads don't get packed into a single bytes array, but instead is treated as a list of multiple bytes arrays.
- Add tests to ensure codecs work properly in both gRPC and REST
=> Fix gRPC encoding for BYTES payloads

mlserver/cli/main.py, mlserver/cli/serve.py, mlserver/handlers/model_repository.py, mlserver/registry.py, mlserver/repository.py, mlserver/rest/server.py, mlserver/rest/utils.py, mlserver/server.py, runtimes/alibi-explain/mlserver_alibi_explain/alibi_dependency_reference.py, runtimes/alibi-explain/tests/conftest.py, runtimes/mlflow/tests/conftest.py, runtimes/mlflow/tests/rest/conftest.py, tests/cli/test_serve.py, tests/conftest.py, tests/handlers/conftest.py, tests/handlers/test_dataplane.py, tests/handlers/test_model_repository.py, tests/metrics/conftest.py, tests/rest/test_utils.py, tests/test_registry.py, tests/test_repository.py
Fixes #433 
- After loading a new model, refresh existing ones to ensure stale models (i.e. loaded, but not present in the repo anymore) get unloaded.
- When (re)loading an existing model (i.e. same name and version, but potentially different artifacts), unload the previous instance of the model.
- Ensure that default model (i.e. reached when there's no version in the URI path) points to the "latest" version, where latest is the highest integer version (if all versions are integers), or the lexicographically highest version (if all versions are not integers).
- Allow models to be loaded from folders named after the model's version (note that this won't change the model version!!).
=> Initial changes to allow loading of multiple versions

mlserver/parallel.py, mlserver/settings.py, tests/test_parallel.py
This PR will add a conditional option to force the ProcessPoolExecutor workers to run the initializer before "loading" is complete (i.e. the server endpoint will wait for all the process workers to load the model). This cuts down on initial inference request latency significantly see below:
```
❯ hey \
-n 10 \
-c 5 \
-m POST \
-T 'application/json' \
-D ./data/iris/rest-requests.json \
http://localhost:8080/v2/models/iris/infer
Summary:
Total:	0.8286 secs
Slowest:	0.4160 secs
Fastest:	0.4090 secs
Average:	0.4133 secs
Requests/sec:	12.0690
Total data:	1950 bytes
Size/request:	195 bytes
Response time histogram:
0.409 [1]	|■■■■■■■■■■■■■
0.410 [0]	|
0.410 [0]	|
0.411 [0]	|
0.412 [1]	|■■■■■■■■■■■■■
0.412 [0]	|
0.413 [1]	|■■■■■■■■■■■■■
0.414 [3]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
0.415 …
```
=> feat: add warm worker pool capability

mlserver/cli/constants.py
**What this PR does / why we need it**:
We discovered an issue when building images using `mlserver build my_model -t some_model:latest` where the conda environment quietly fails and the environment is not loaded into the second stage properly. By building the image ourselves (using Docker directly) we discovered that a `CondaPackError` was raised which didn't cause the `/envs/base.tar.gz` to compress properly. The tarball then didn't unpacked correctly and the conda env failed to load once the docker was run which raises the same error as described in #476.
This error was also described in https://github.com/conda/conda-pack/issues/98 which caused us to test the change in this PR, where the conda-pack fails to resolve environments between pip and conda.
**Which issue(s) this PR fixes**: …
=> #476: missing flag added to conda-pack

mlserver/errors.py, mlserver/grpc/servicers.py, mlserver/rest/errors.py, tests/grpc/test_servicers.py, tests/rest/test_endpoints.py
Currently MLServer returns a 400 HTTP response or `INVALID_ARGUMENT` gRPC response in all error cases. It would be useful to distinguish between different classes of error, in particular indicating the model-not-found case with a 404 or gRPC `NOT_FOUND` status. Model-mesh uses `NOT_FOUND` to take corrective action i.e. re-load the model in question if necessary.
I kept the default value as 400 for `MLServerError` subclasses that don't provide a specific code, but maybe something else like 500 would be more appropriate?
Note that this is affected by https://github.com/SeldonIO/MLServer/pull/487 but I can fix this one up after that's merged.
=> More accurate REST/gRPC response status codes for errors

docs/user-guide/adaptive-batching.md
Signed-off-by: Peixuan Ding <dingpeixuan911@gmail.com>
Hi, Thanks for creating this tool! I've been exploring this over the weekend and found a few mistakes in the docs.
Apparently, the fields for adaptive batching are called `max_batch_...` instead of `maximum_batch_...`, see the code below:
https://github.com/SeldonIO/MLServer/blob/a4ea7cb6d85cc696db2b042c0e7ce0a2950760e8/mlserver/settings.py#L147-L152
Thanks!
=> Fix docs for adaptive batching

mlserver/codecs/numpy.py, mlserver/codecs/pandas.py, tests/codecs/test_pandas.py
While testing MLServer in Seldon Core, I discovered a bug due to which the datatype sent in the request input is not used to create the dataframe. Instead it uses the default data types in Pandas which do not include `int32`. This PR proposes a fix for this bug. 
The change has been tested using unit tests and locally by running mlserver. 
Related slack thread - https://seldondev.slack.com/archives/C8Y9A8G0Y/p1645517701847759?thread_ts=1645093614.150229&cid=C8Y9A8G0Y
=> Use dtype in the request to create input DataFrame

runtimes/alibi-explain/tests/conftest.py, runtimes/lightgbm/tests/conftest.py, runtimes/mlflow/tests/conftest.py, runtimes/sklearn/tests/conftest.py, runtimes/xgboost/tests/conftest.py, setup.cfg, tests/conftest.py
Update `pytest-asyncio`'s config so that it uses the new [auto mode](https://github.com/pytest-dev/pytest-asyncio#auto-mode), which also removes a warning from the tests.
=> Update default config for pytest-asyncio

runtimes/alibi-explain/tests/test_black_box.py
- Use `assert_allclose` instead of `assert_array_equal` to allow an error tolerance
=> Fix flakiness in Alibi's end-to-end 

runtimes/alibi-explain/tests/test_black_box.py
Adjust `assert_allclose` tolerance in Alibi tests to account for flaky tests. The values have been taken from the [output when the tests fail](https://github.com/SeldonIO/MLServer/runs/5409917772?check_suite_focus=true#step:5:319):
```
E  AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=0
E       
E       Mismatched elements: 87 / 784 (11.1%)
E       Max absolute difference: 227
E       Max relative difference: 1.
E        x: array([[[161],
E               [171],
E               [ 97],...
E        y: array([[[161],
E               [171],
E               [ 97],...
```
=> Increase error tolerance to adjust for flaky tests

README.md, mlserver/batching/requests.py, tests/conftest.py, tests/grpc/test_converters.py, tests/testdata/inference-request-with-output.json, tests/testdata/inference-response-with-output.json
Address #514.
Parameterise the test fixtures `inference_request` and `inference_response` to test inference requests with outputs.
=> fix: Adaptive Batching ignoring requested output

mlserver/model.py
With current setting, the return meta data for `outputs` is taken from `inputs` one.
=> fix: Correct return MLModel setting for outputs

hack/generate_dotenv.py
- New method to parse the only BaseSetting that might involve a JSON / dict object 
- Replaces single quotes within value with doubles
- Replaces double quotes around the environment variable with singles
- Tested outputs in a docker image with some custom extra dictionary and starts server
=> Added _parse_dict_values method

mlserver/handlers/dataplane.py, tests/metrics/test_endpoint.py
This PR relates to ticket Tag model-specific Prmoetheus metics #457 
https://github.com/SeldonIO/MLServer/issues/457
These changes create a new Prometheus metric for each model inference which is prefixed with "model_infer_request_". This metric is tagged with the model name and the model version.
=> Tag Prometheus metrics with model name and version

mlserver/rest/server.py
If no custom logging config has been provided, let Uvicorn fall back to their own defaults.
=> Fix logging default

runtimes/huggingface/setup.py
Addresses one of the followups from the improvements identified from the huggingface runtime, namely upgrading to the pinned 1.2.0 verison of optimum as outlined in #576
=> Updating HuggingFace Optimum library to v1.2.0

mlserver/registry.py, mlserver/server.py, tests/conftest.py, tests/rest/test_codecs.py, tests/test_registry.py
Add a new set of model reload hooks to ensure that models don't get removed from parallel workers when reloading an existing model.
=> Add model reload hooks

mlserver/parallel/pool.py, mlserver/registry.py, mlserver/server.py, tests/cli/conftest.py, tests/cli/test_start.py, tests/fixtures.py, tests/metrics/conftest.py, tests/test_registry.py, tests/testdata/models.py, tests/utils.py
Part of #576 
- Ensure that the server's health endpoints are exposed before starting to load the initial set of models
- Ensure that models show as "not ready" while they are getting loaded
- To refresh / reload existing models, ensure that we do a "rolling update" (i.e. keep the old version available while we load the new one)
=> Improve logic for health endpoints

runtimes/huggingface/mlserver_huggingface/common.py, runtimes/huggingface/mlserver_huggingface/runtime.py
Fixes part of #576 
* Ensuring the transformer model is downloaded async and cached
* Model then gets loaded without affecting liveness/readiness probes
* Allows for very large transformers to be loaded
* Uses the Optimum SUPPORTED_TASKS object
=> Ensure HuggingFace runtime doesn't block asyncio when loading model

runtimes/huggingface/mlserver_huggingface/common.py
Part of #576
As per discussion in https://github.com/huggingface/optimum/issues/186 it is no longer necessary to pass an env manually as the XDG env var would be enough to cover the cache folder case.
=> Removed cache folder for Hugging Face Runtime as no longer required

mlserver/rest/server.py, mlserver/settings.py
As discussed in #571, this adds support for configuring the Uvicorn `root_path` parameter. I looked through the tests and saw that most settings don't have specific unit tests attached, but I've tested this setting on one of my applications and it works as expected.
Please let me know if any other info is required.
=> Add Uvicorn root_path configuration

mlserver/batching/adaptive.py, mlserver/parallel/worker.py, mlserver/server.py, runtimes/alibi-explain/setup.py, setup.cfg, tests/conftest.py, tests/parallel/conftest.py
It looks like Uvloop tries to terminate all subprocesses by itself through signals. However, we want the main process to handle that, so that we can ensure a clean shutdown of the inference workers. To account for that, this PR ensures that the workers ignore upstream signals.
=> Fix some Uvloop quirks

tests/utils.py
- Retry requests if there's a connection error (which could just indicate that the docker container is still coming up).
=> Address flakiness in build subcommand tests

mlserver/cli/build.py, mlserver/cli/main.py
Attempting to give users the option to use docker build cache or not, this is useful in development of multiple model versions but also in keeping a CI / CD environment clean.
* Added new -n / --no-cache option to mlserver build
* Added --rm option explicitly to ensure intermediate containers are deleted after successful build
Should fix #604
=> Adding --no-cache / -n option to mlserver build

mlserver/grpc/server.py, mlserver/metrics/__init__.py, mlserver/metrics/server.py, mlserver/parallel/pool.py, mlserver/rest/app.py, mlserver/rest/server.py, mlserver/server.py, mlserver/settings.py, tests/cli/conftest.py, tests/cli/test_build.py, tests/cli/test_start.py, tests/metrics/conftest.py, tests/metrics/test_endpoint.py, tests/metrics/test_rest.py, tests/metrics/utils.py
Fixes #458 
- Move metrics endpoint into its own FastAPI server
- Add new `metrics_port` field to set the port for the new metrics server 
- Minor fixes to ensure workers get shut down correctly
=> Move metrics endpoint into its own server

mlserver/grpc/converters.py, mlserver/grpc/dataplane_pb2.py, mlserver/grpc/dataplane_pb2.pyi, mlserver/grpc/dataplane_pb2_grpc.py, mlserver/grpc/model_repository.py, mlserver/grpc/server.py, mlserver/grpc/servicers.py, mlserver/grpc/utils.py, proto/dataplane.proto, tests/grpc/conftest.py, tests/grpc/test_converters.py, tests/grpc/test_model_repository.py, tests/grpc/test_servicers.py
Fixes #600 
- Merge model repository endpoints with data plane's service
- Keep previous model repository API but flag as deprecated (will be removed in MLServer 1.2.0)
=> Update protobuf to include control plane

mlserver/codecs/pandas.py, tests/codecs/test_pandas.py
Allows decoding a `None` into `np.NaN` and correctly uses the datatype when creating each series.
LightGBM will train [missing data with NaN values](https://lightgbm.readthedocs.io/en/latest/Advanced-Topics.html#missing-value-handle) by default, but if my call to infer has only None value(s) for an input that was trained as a floating point, I get the error:
```
ValueError: DataFrame.dtypes for data must be int, float or bool.
Did not expect the data types in the following fields: column
```
The `datatype` is not used when the PandasCodec receives a `None` value.  Tracing this down, [`mlserver.codecs.pandas._to_series()`](https://github.com/SeldonIO/MLServer/blob/24917089d0f7acd62ad84b63b3862200af03ce74/mlserver/codecs/pandas.py#L14) only calls  `mlserver.codecs.numpy.to_dtype()` when …
=> Always use to_dtype when decoding the pandas Series

.github/workflows/benchmark.yml
To avoid getting PRs failing checks due to fluctuations in GH workers performance, instead of running benchmarks for every PR, we will run them periodically every day.
=> Run benchmarks every day

mlserver/repository.py
If a folder disappears during model load this can cause an exception.
https://github.com/SeldonIO/MLServer/blob/acae8a77c04b339c1346775456ab241d80a276fe/mlserver/repository.py#L28-L29
The glob returns all model-settings files. If between this time and the time of a load the file disappears this will cause an exception 
https://github.com/SeldonIO/MLServer/blob/acae8a77c04b339c1346775456ab241d80a276fe/mlserver/repository.py#L31-L33
This fix ignores these exceptions for loading model settings files.
In future, it may be better to try to find the model to load in a more directed way rather than searching the whole repository.
=> handle missing model settings folders during load

runtimes/huggingface/setup.py, runtimes/huggingface/tests/conftest.py, runtimes/huggingface/tests/test_runtime.py
Following this PR from Optimum https://github.com/huggingface/optimum/pull/210, the Huggingface runtime will raise an error complaining about a missing `deepspeed_reinit` import. 
This PR bumps the version of the `optimum` package to the latest version, which includes a fix for the above..
=> Fix deepspeed_reinit error

runtimes/alibi-detect/mlserver_alibi_detect/runtime.py
The [example inference request in the alibi-detect docs notebook](https://github.com/SeldonIO/MLServer/tree/master/docs/examples/alibi-detect#send-test-inference-request) uses `numpy` content-type as the parameter(default).
The same example should be working with a `pd` content-type using the example request below. The main reason for failure is that the alibi-detect library expects a numpy array as input for prediction. This PR adds that conversion logic in the runtime.
```
{
"parameters": { "content_type": "pd" },
"inputs": [
{
"name": "Age",
"shape": [1, 1],
"datatype": "FP32",
"data": [53]
},
{
"name": "Workclass",
"shape": [1, 1],
"datatype": "INT64",
"data": [4]
},
{
"name": "Education",
"shape": [1, 1],
"datatype": "INT64",
"data": [0]
},
{
"name": "Marital Status",
"shape": [1, …
```
=> Converting alibi detect input to numpy array format before prediction

requirements/dev.txt
=> Revert "Bump grpcio-tools from 1.47.0 to 1.48.0"

mlserver/rest/app.py, mlserver/settings.py
This PR moves the string prefix "_rest_server_", currently hardcoded to settings, keeping its default value as _rest_server_.
Because we currently set up our application prefixes as "_http_application_" this can be achieved with MLServer by removing the hardcoded string.
cc @adriangonz
=> Add support to configurable metrics_rest_server_prefix

mlserver/settings.py, tests/parallel/test_messages.py
Follow up from #693 to work around Python's internal `sys.modules` cache.
=> Ensure module gets reloaded before loading model

docs/examples/custom/README.ipynb, docs/examples/custom/README.md
=> custom server requirements.txt file generation added to the notebook

runtimes/huggingface/mlserver_huggingface/runtime.py, runtimes/huggingface/setup.py, runtimes/huggingface/tests/test_runtime.py
Fixes issue discussed in [community Slack](https://seldondev.slack.com/archives/C03DQFTFXMX/p1663522460764359), where the HF runtime was aggregating all the batch outputs into a single entry.
=> Ensure HF runtime encodes batches separately 

Dockerfile, mlserver/cli/constants.py
- Use `unattended-upgrades` to apply security updates to base image
- Bump version of `miniconda3` image
=> Fix CVEs in base image

runtimes/alibi-explain/mlserver_alibi_explain/common.py, runtimes/alibi-explain/mlserver_alibi_explain/explainers/black_box_runtime.py, runtimes/alibi-explain/tests/test_alibi_runtime_base.py, runtimes/alibi-explain/tests/test_utils.py
This allows server certificates to be verified in `requests` calls when MLServer might need to custom ca.crt file. The path to this ca.crt file can now be specified in the model-settings.json.
This is needed for correct TLS usage where black box explainers may call an endpoint whose certificate chain MLServer needs
=> Add ssl_verify_path to explainers

Dockerfile, hack/activate-env.sh, hack/build-env.sh, hack/generate_dotenv.py, mlserver/cli/constants.py, tests/testdata/env_models.py, tests/testdata/environment.yml
Fixes #722 
- Update build scripts to let `python-dotenv` do its thing. This ensures that env vars can still override the default model settings after the custom image has been created.
The build scripts are coming from the base `seldonio/mlserver:1.2.0.dev6-slim` image. Therefore, the `mlserver build` tests will fail, since they're not able to get the updated config scripts. I've tested these locally though, and seem to work OK :+1: 
Once the tests finish (with those failing ones), we'll go ahead and merge this PR, and then kick off a `1.2.0.dev7` build, which should sort out these errors.
=> Use python-dotenv to manage default env in custom images

mlserver/batch_processing.py, mlserver/batching/requests.py, mlserver/cli/main.py, tests/batch_processing/test_rest.py
Add micro-batching to `mlserver infer` in order to align with v1 batch processor.
Noticeable changes:
- input/output queues now holds `List[BatchInputItem]` and `List[BatchOutputItem]`
- added separate preprocess / postprocess functions
- added `TritonRequest` class (one step closer towards Triton codecs)
=> Micro batching

Dockerfile, runtimes/alibi-explain/mlserver_alibi_explain/common.py, runtimes/alibi-explain/mlserver_alibi_explain/explainers/black_box_runtime.py, runtimes/alibi-explain/tests/test_black_box.py, runtimes/huggingface/mlserver_huggingface/runtime.py
1. Exclude unset fields when sending inference requests to limit issues on deserialization on the server end
2. Set use_bytes when creating input to send to ensure it can be JSON serialized
3. Exclude SCV2 pipelines when asking for metadata as this is not presently possible with Pipelines
4. Use `args` not `*args` in Huggingface runtime as `args` is always a single argument or list. Allows batch inputs to work.
=> Alibi Explain Update to work with Hugging face runtime

Dockerfile
Fixes #807 
Temporarily excluding MLlib from main image due to the following CVEs:
-   CVE-2022-25168
-   CVE-2022-42889
Note that MLlib will still be present in the `seldonio/mlserver:X.X.X-mllib` runtime-specific image.
=> Temporarily excluding mllib from main image

docs/user-guide/content-type.md, mlserver/codecs/base64.py, mlserver/codecs/datetime.py, mlserver/codecs/numpy.py, mlserver/codecs/pandas.py, mlserver/codecs/string.py, mlserver/codecs/utils.py, runtimes/alibi-explain/mlserver_alibi_explain/common.py, runtimes/alibi-explain/mlserver_alibi_explain/runtime.py, runtimes/alibi-explain/tests/test_alibi_runtime_base.py, runtimes/alibi-explain/tests/test_black_box.py, runtimes/alibi-explain/tests/test_common.py, runtimes/mlflow/tests/test_codecs.py, runtimes/mlflow/tests/test_runtime.py, tests/codecs/test_base64.py, tests/codecs/test_datetime.py, tests/codecs/test_decorator.py, tests/codecs/test_numpy.py, tests/codecs/test_pandas.py, tests/codecs/test_string.py, tests/codecs/test_utils.py, tests/grpc/test_codecs.py, tests/rest/test_codecs.py, tests/test_raw.py
Fixes #818 
- To avoid room for ambiguity, where a shape is set to `[N]`, convert it to `[N, 1]` (which is MLServer's assumption). This will be switched on in some codecs (`StringCodec`, `Base64Codec`, `DatetimeCodec` and `PandasCodec`).
=> Set explicitly a two-dimensional shape on some codecs

runtimes/alibi-explain/tests/test_utils.py
Latest version of FastAPI dropped the `verify` kwarg of the TestClient, which is used in the Alibi-Explain runtime tests. This PR ensures this doesn't break the tests.
=> Fix tests for latest version of FastAPI

runtimes/alibi-explain/mlserver_alibi_explain/explainers/black_box_runtime.py
As a follow up to #818, Alibi doesn't seem to like model response tensors shaped as `[N, 1]` (i.e. with an explicit dimensionality shape). To work around these, process response tensors within the Alibi runtime to detect and remove these explicit empty shapes.
=> Fix issue with empty dimensions

runtimes/huggingface/setup.py
It seems like recent versions of `optimum` expect a newer version of `transformers`. Otherwise it will show the error below:
```
.tox/all-runtimes/lib/python3.9/site-packages/transformers/utils/import_utils.py:1004: in _get_module
raise RuntimeError(
E   RuntimeError: Failed to import optimum.onnxruntime.modeling_seq2seq because of the following error (look up to see its traceback):
E   cannot import name 'TFAutoModelForSemanticSegmentation' from 'transformers.models.auto' (/home/agm/Seldon/mlserver/.tox/all-runtimes/lib/python3.9/site-packages/transformers/models/auto/__init__.py)
```
=> Add dep bounds in HF runtime

Dockerfile, requirements/dev.txt
Pin setuptools in `Dockerfile` and tests to work around a breaking change in `setuptools==65.6.0` (https://github.com/pypa/setuptools/issues/3693).
=> Pin setuptools

mlserver/parallel/utils.py, runtimes/alibi-explain/mlserver_alibi_explain/common.py, runtimes/alibi-explain/mlserver_alibi_explain/runtime.py, runtimes/alibi-explain/tests/helpers/run_async.py, runtimes/alibi-explain/tests/test_alibi_runtime_base.py, runtimes/alibi-explain/tests/test_black_box.py
It seems that using the default executor when calling `loop.run_in_executor` can lead to strange issues in some cases. This PR ensures that we explicitly create an executor for the Alibi runtime, which gets used instead of the default one.
=> Use explicit executor in Alibi runtime

docs/examples/custom-json/README.ipynb, docs/examples/custom-json/README.md
updates based on https://github.com/SeldonIO/MLServer/pull/785
=> updated grpc example based on recent updates

mlserver/codecs/base.py, tests/codecs/test_base.py
Any unexpected input in the content_type parameter field on either input or request will crash the server otherwise and return a 500.
=> fix(codecs): do not crash when the content type is not registered

mlserver/parallel/errors.py, mlserver/parallel/worker.py, tests/parallel/test_errors.py, tests/parallel/test_model.py, tests/parallel/test_pool.py, tests/parallel/test_worker.py
Fixes #881 
- Workers will now always return instances of `WorkerError`, which only contain the original error message. The stacktrace will still get printed as part of the worker logs.
=> Add WorkerError wrapper to avoid issues pickling exceptions

README.md, docs/runtimes/alibi-explain.md, docs/runtimes/index.md, runtimes/alibi-explain/README.md
=> Add Alibi Explain to list of runtimes

.github/workflows/benchmark.yml
This job often run on forks producing unnecessary noise
=> do not run benchmark job on forks

mlserver/batching/requests.py, tests/batching/test_requests.py
fixes #915
aggregate batch requests of:
```python
payload = types.InferenceRequest(
inputs=[
types.RequestInput(
name="parameters-np",
shape=[1],
datatype="BYTES",
data=[],
parameters=types.Parameters(
custom-param='value-1,
)
]
)
payload = types.InferenceRequest(
inputs=[
types.RequestInput(
name="parameters-np",
shape=[1],
datatype="BYTES",
data=[],
parameters=types.Parameters(
custom-param='value-2',
)
]
)
```
as follows:
`{custom-param=['value-1', 'value-2']`
instead of overwriting the `value-1` with `value-2`
=> common batch parameters stored in a list

setup.py
Fixing MLServer blocking incompatibility with the recent update of FastAPI https://github.com/tiangolo/fastapi/releases/tag/0.89.0
=> fixing FastAPI incompatibility

runtimes/huggingface/mlserver_huggingface/codecs/base.py, runtimes/huggingface/mlserver_huggingface/codecs/utils.py, runtimes/huggingface/tests/test_codecs/test_base.py, runtimes/huggingface/tests/utils.py
1. Error happend when a run a `image-segmantation` task. The Pillow Image pipeline output has not format. So add a default one
2. If client give a invalid content_type, the default_codec may be None, caused runtime error
=> bugfix, set a default image format when Pillow image has no format

setup.py
Fixes #935
FastAPI `0.89.0` introduced a breaking issue, which is now fixed in `0.89.1` (see https://github.com/tiangolo/fastapi/issues/5861). 
This PR bumps the ceiling to `0.89.1`, skipping the `0.89.0` release.
=> Bump FastAPI to 0.89.1 (keeping the ceiling)

runtimes/huggingface/mlserver_huggingface/common.py, runtimes/huggingface/mlserver_huggingface/runtime.py, runtimes/huggingface/tests/test_common.py
Fixes #947
When I run huggingface task translation, got this `raise ValueError('The task defaults can\'t be correctly selected. You probably meant "translation_XX_to_YY"')`
So, I add a new setting item in HuggingfaceSetting, to support task name suffix.
=> support huggingface translation task suffix

runtimes/alibi-explain/mlserver_alibi_explain/runtime.py
Currently we have been converting all inputs to numpy before passing them to alibi `explain` method. This is not true in the case of `AnchorText` as it expects an `str`, check [here](https://docs.seldon.io/projects/alibi/en/latest/api/alibi.explainers.html#alibi.explainers.AnchorText.explain).
Although we should be perhaps more strict in the way we do the conversions between types but for now we know we want to convert pd.DataFrame to numpy which we do explicitly.
=> Only convert pd.DataFrame to numpy array in alibi-explain

.dockerignore, .gitignore, mlserver/rest/app.py, mlserver/rest/requests.py, setup.cfg, tests/rest/test_custom.py
Second pull request fix for #931
I add gzip decompress for requests if has header Content-Encoding
- Add gzip decompress for Request to custom Request class
- Add unit test for gzip request
=> Add rest request gzip decompress

docs/examples/mms/README.md
Adding a link to the blog post on MMS on the seldon.io domain. This is mostly for SEO purposes and was requested by marketing. Seems fairly harmless.
=> adding SEO link

mlserver/batching/requests.py, tests/batching/test_requests.py
fixes #923
Could be improved by solving https://github.com/SeldonIO/MLServer/issues/924
=> added split of batched params

setup.cfg, setup.py
Force `protobuf==3.20.3` to include patch for CVE-2022-1941. 
Related to https://github.com/huggingface/optimum/issues/733
=> Force patch for CVE-2022-1941

.gitignore, mlserver/handlers/dataplane.py, mlserver/metrics/__init__.py, mlserver/metrics/prometheus.py, mlserver/metrics/server.py, mlserver/parallel/__init__.py, mlserver/parallel/pool.py, mlserver/parallel/worker.py, mlserver/server.py, mlserver/settings.py, tests/metrics/conftest.py, tests/metrics/test_custom.py, tests/metrics/test_grpc.py, tests/metrics/test_prometheus.py, tests/metrics/test_rest.py
Part of #303 
Note that this work just enables the collection of metrics across multiple workers, which lets users define Prometheus metrics directly on their custom runtimes. However, we may still introduce a simplified way to register metrics within the MLServer package itself (e.g. `self.metrics.register('foo', 1)`) - which is why this PR doesn't close #303 (and also why there is no docs update in this PR). 
- Enable Prom's multiprocess mode when `parallel_workers > 0`, adding a new `metrics_dir` setting.
- Clean up `*.db` files during shutdown.
- Add tests around manual set up of custom metrics in custom runtimes.
=> Add support for Prometheus metrics across multiple processes

mlserver/batching/__init__.py, runtimes/alibi-detect/README.md, runtimes/alibi-detect/mlserver_alibi_detect/runtime.py, runtimes/alibi-detect/tests/conftest.py, runtimes/alibi-detect/tests/test_drift_detector.py, runtimes/alibi-detect/tests/test_outlier_detector.py, runtimes/alibi-detect/tests/test_runtime.py
Fixes #1019
- Add the `batch_size` flag to the Detect settings.
- Use the `BatchedRequests` utility class within the Detect runtime to accumulate batches.
=> Support batch accumulation within Detect runtime

.github/workflows/benchmark.yml, .github/workflows/publish.yml, .github/workflows/release-sc.yml, .github/workflows/release.yml, .github/workflows/security.yml, .github/workflows/tests.yml, CHANGELOG.md, RELEASE.md, docs/changelog.md, docs/index.md
Fixes #1032
- Add initial `CHANGELOG.md`, generated from published GH releases.
- Add GH action to update `CHANGELOG.md` everytime a new release is published.
- Add `stable` tag, which points to the latest published release in GH.
=> Add CHANGELOG.md and GH action to auto-generate it

mlserver/codecs/decorator.py, tests/codecs/test_decorator.py
Fixes #1036 
I'm unsure how/where to add a test for this as I didn't manage to run the test suite. Locally, I've experimented with the following snippet.
```python
from typing import Tuple
import numpy as np
from mlserver.codecs.decorator import SignatureCodec
def predict_fn_typing_tuple() -> Tuple[np.ndarray, np.ndarray]:
return (np.array([4]), np.array([2]))
def predict_fn_native_tuple() -> tuple[np.ndarray, np.ndarray]:
return (np.array([4]), np.array([2]))
def predict_fn_tuple_object() -> (np.ndarray, np.ndarray):
return (np.array([4]), np.array([2]))
def test_typing_tuple():
signature_codec = SignatureCodec(predict_fn_typing_tuple)
assert signature_codec._output_hints == [np.ndarray, np.ndarray]
def test_native_tuple():
signature_codec = SignatureCodec(predict_fn_native_tuple)
assert …
```
=> Fix signature codec with tuple type annotations

docs/examples/huggingface/README.ipynb, docs/examples/huggingface/README.md, runtimes/huggingface/README.md, runtimes/huggingface/mlserver_huggingface/common.py, runtimes/huggingface/mlserver_huggingface/errors.py, runtimes/huggingface/mlserver_huggingface/runtime.py, runtimes/huggingface/mlserver_huggingface/settings.py, runtimes/huggingface/setup.py, runtimes/huggingface/tests/conftest.py, runtimes/huggingface/tests/test_common.py, runtimes/huggingface/tests/test_runtime.py, runtimes/huggingface/tests/test_runtime_cases.py
Fixes #870
Fixes #852
Fixes #786
- Use `accelerator='ort'` to load Optimum models (as opposed to previous `from_transformers=True` kwarg)
- Document available HuggingFace extra settings
- Enable GPU usage for Optimum models
=> Improvements for HuggingFace runtime

Dockerfile
This PR explicitly removes a `requirements.txt` file from spaCy's test suite causing false positives in Snyk
=> Remove spaCy's test requirements.txt

.github/workflows/release-sc.yml, .github/workflows/release.yml, .github/workflows/security.yml
Now that the image size has been considerably shrinked, we can try to undo the changes to the release and security pipelines.
=> Undo changes to pipelines

Dockerfile, MANIFEST.in, docs/conf.py, mlserver/rest/openapi/__init__.py, mlserver/rest/openapi/dataplane.json, mlserver/rest/openapi/model_repository.json, mlserver/rest/openapi/schema.py, mlserver/version.py, runtimes/alibi-detect/mlserver_alibi_detect/version.py, runtimes/alibi-explain/mlserver_alibi_explain/version.py, runtimes/huggingface/mlserver_huggingface/version.py, runtimes/lightgbm/mlserver_lightgbm/version.py, runtimes/mlflow/mlserver_mlflow/version.py, runtimes/mllib/mlserver_mllib/version.py, runtimes/sklearn/mlserver_sklearn/version.py, runtimes/xgboost/mlserver_xgboost/version.py, tests/rest/openapi/test_schema.py
Fixes #1093 
- Add OpenAPI schema under `mlserver.rest.openapi` package as symbolic links (i.e. files in root repo remain source-of-truth)
=> Move OpenAPI schemas into Python package

mlserver/parallel/registry.py, runtimes/alibi-explain/tests/conftest.py, runtimes/mlflow/tests/rest/conftest.py, tests/grpc/conftest.py, tests/rest/conftest.py
Fixes #1101 
- When loading a model, use the default initialiser if the model doesn't use any custom environments
=> Use default initialiser if not using a custom env

runtimes/alibi-detect/mlserver_alibi_detect/runtime.py, runtimes/alibi-detect/tests/conftest.py, runtimes/alibi-detect/tests/test_drift_detector.py, runtimes/alibi-detect/tests/test_runtime.py
This PR adds support for [online drift detectors](https://docs.seldon.io/projects/alibi-detect/en/stable/cd/methods.html#online) to Alibi Detect runtime. 
This involves two primary changes:
1. Online drift detectors are run on one instance at a time, with the time-step `self.t` updated each time. If a request contains a batch of instances, the payload must be unpacked and passed to the detector one instance at a time.
2. Online drift detectors have state, which must be periodically saved for checkpointing. State is saved every `state_save_freq` time-steps, where `state_save_freq` is a new configurable parameter added to `AlibiDetectSettings`.
Parallel inference is NOT currently supported for online detectors (i.e. `parallel_workers=0` is required). This would require careful thought wrt …
=> Add support for online drift detectors

Dockerfile
Set a default value for the `LD_LIBRARY_PATH` env var to ensure the CUDA libraries injected at run-time by GKE can be found.
=> Add default LD_LIBRARY_PATH env var

mlserver/parallel/dispatcher.py
The last return line of the `_wait_response` method seems to be unreachable (?)
=> Unreachable line

mlserver/codecs/base64.py, mlserver/codecs/datetime.py, mlserver/codecs/numpy.py, mlserver/codecs/pandas.py, mlserver/codecs/utils.py, runtimes/mlflow/mlserver_mlflow/codecs.py, runtimes/mlflow/tests/test_codecs.py, runtimes/mlflow/tests/test_runtime.py, tests/codecs/test_base64.py, tests/codecs/test_datetime.py, tests/codecs/test_decorator.py, tests/codecs/test_numpy.py, tests/codecs/test_pandas.py, tests/codecs/test_utils.py, tests/grpc/test_codecs.py, tests/rest/test_codecs.py
Fixes #737
- Ensure encode methods in `PandasCodec` always add the `content_type: pd` and `content_type: str` as needed.
=> Fix content type annotations for pandas codecs

docs/reference/api/index.md
`a python packaged` -> `a python package`
=> Fix small typo in Python API docs

.github/workflows/tests.yml
Recent versions of OpenMP (i.e. >= 12) cause segfaults in MacOS when training LightGBM / XGBoost models (but only when Torch is present). This PR downgrades OpenMP to an older version (i.e. == 11). 
See https://github.com/microsoft/LightGBM/issues/4229 and https://github.com/autogluon/autogluon/issues/1442 for more details.
=> Add workaround for segfault in MacOS tests

.github/workflows/benchmark.yml, .github/workflows/licenses.yml, .github/workflows/release.yml, .github/workflows/security.yml, .github/workflows/tests.yml, Dockerfile
Fixes #1072 
- Use `3.10` as default in MLServer images
- Use `3.10` as default in CI Actions
We haven't added support for `3.11` in this PR because there's no `grpcio` pre-built wheel available yet:
https://github.com/grpc/grpc/issues/32454
=> Bump Python to 3.10 as default

docs/reference/api/model.md, docs/user-guide/custom.md, mlserver/model.py, mlserver/registry.py, runtimes/huggingface/mlserver_huggingface/runtime.py, runtimes/huggingface/tests/test_runtime.py, tests/test_registry.py
Fixes #1145 
- Add `unload()` method in `MLModel` interface (called by registry when unloading models)
=> Add unload method to MLModel interface

runtimes/huggingface/README.md, runtimes/huggingface/mlserver_huggingface/codecs/base.py, runtimes/huggingface/mlserver_huggingface/runtime.py, runtimes/huggingface/tests/test_codecs/test_base.py
- Rename multi-input HF codec's content type to `hf` (the previous `str` caused conflicts with MLServer's base one)
- Always use `HuggingfaceRequestCodec` in HF runtime (i.e. ignore top-level request `content_type` annotation)
=> Rename HF codec to `hf`

mlserver/rest/app.py
We noticed recently that our custom `Response` class (using `orjson`) wasn't being used. This PR tweaks that to ensure it does get used again.
=> Make sure we use our Response class

runtimes/huggingface/mlserver_huggingface/settings.py, runtimes/huggingface/tests/test_settings.py
If settings for the model are provided in both the `model-settings.json` *and* environment variables, merge them.
Precedence is given to environment variables.
FIXES #1329
=> feat(huggingface): Merge model settings

docs/user-guide/content-type.md, mlserver/codecs/numpy.py, mlserver/codecs/pandas.py, tests/codecs/test_numpy.py, tests/codecs/test_pandas.py
Fixes #1154
- Add docs around NaN behaviour
- Extend Numpy and Pandas codecs to handle NaNs (only for `FP*` datatypes)
=> Document and test behaviour around NaN

Dockerfile
- Update Conda to bump the included `requests` lib to `2.31.0+` to sort out CVE-2023-32681
=> Bump Miniforge3 to 23.3.1

runtimes/sklearn/README.md
Fixing a very minor typo (`availabe` -> `available`) in the `sklearn` docs
=> Fix minor typo in `sklearn` README

runtimes/huggingface/mlserver_huggingface/common.py, runtimes/huggingface/mlserver_huggingface/settings.py, runtimes/huggingface/tests/test_common.py
This is for issue [1344](https://github.com/SeldonIO/MLServer/issues/1344)
This allow `model-settings.json` to take `model_kwargs`:
example below:
```json
{
"name": "llama",
"implementation": "mlserver_huggingface.HuggingFaceRuntime",
"parameters": {
"extra": {
"task": "text-generation",
"pretrained_model": "daryl149/llama-2-7b-hf",
"model_kwargs": {
"device_map": "auto",
"load_in_8bit": true
}
}
}
}
```
=> added model_kwargs to huggingface model

.github/workflows/tests.yml
There is a missing quote that made the CI fail. This is impacting tests that run post-merge to `master` for py3.9.
=> fix(ci): Missing quote in CI test for all_runtimes

Dockerfile
Reduces exposure to CVEs.
**Testing**
`$ make build`
```
docker run --rm -it seldonio/mlserver:1.5.0.dev1 pip list | grep cryptography
```
Looks like the cryptography package isn't there?
It does have other packages, as expected:
```
$ docker run --rm -it seldonio/mlserver:1.5.0.dev1 pip list | grep huggingface
huggingface-hub                          0.21.3
mlserver-huggingface                     1.5.0.dev1
```
```
$ docker run --rm -it seldonio/mlserver:1.5.0.dev1 pip list | grep catboost
catboost                                 1.2.3
mlserver-catboost                        1.5.0.dev1
```
=> build(docker): Bump dependencies

README.md
> Python 3.8 is due to reach its scheduled upstream end-of-life in October 2024.
In preparation for this, we're marking support for this version as deprecated. It's still available, but will be removed in a future version.
=>  docs: List supported Python versions 

.github/workflows/release.yml
Currently we have a task `mlserver` that:
- build python wheels and push to pypy
- build and scan mlserver big image
- build and scan mlserver slim image
This change breaks them up into individual steps as we started running out of disk space.
=> fix(ci): Have separate smaller tasks for release

runtimes/huggingface/mlserver_huggingface/settings.py, runtimes/huggingface/tests/test_common.py
If using a `model-settings.json` of the following form:
```json
{
"name": "my-model",
"implementation": "mlserver_huggingface.HuggingFaceRuntime",
"parameters": {
"extra": {
"task": "text-generation",
"pretrained_model": "model/path",
"model_kwargs": {
"load_in_8bit": true
}
}
}
}
```
an error occurs when spinning up the server:
```
The model has been loaded with `accelerate` and therefore cannot be moved to a specific device. Please discard the `device` argument when creating your pipeline object.
```
because the `load_in_8bit` model kwarg makes forces the model to be loaded with Accelerate, and `HuggingFaceSettings.device` default value of -1 is passed. I tried simply passing `"device": null` to the model settings json to prevent this default value, but this wasn't accepted because the …
=> Fix mlserver_huggingface settings device type

.github/workflows/release-sc.yml, .github/workflows/release.yml, .github/workflows/security.yml, .github/workflows/tests.yml
This change introduces the use of `overprovision-lvm` (instead of setting `root-reserve-mb`) to optimise disk space for the docker build actions, which is the recommendation described here 
from the action [docs](https://github.com/easimon/maximize-build-space/tree/master/).
=> fix(ci): optimise disk space for GH workers

.github/workflows/publish.yml, OWNERS, OWNERS_ALIASES
Doing some cleanup. This matches the reviewers in the Dependabot config [1].
[1] https://github.com/jesse-c/MLServer/blob/eefbb430870b994f223251f4d8b988482ea18163/.github/dependabot.yml#L72
=> build: Update maintainers

.github/dependabot.yml
It wasn't listed, as the other runtimes were.
=> build: Add Catboost runtime to Dependabot

docs/user-guide/content-type.md
Closes #1678 
Fixes JSON Payload input shapes in Pandas DataFrame content type section of User Guide.
For example DataFrame:
| A   | B   | C   |
| --- | --- | --- |
| a1  | b1  | c1  |
| a2  | b2  | c2  |
| a3  | b3  | c3  |
| a4  | b4  | c4  |
All inputs in JSON payload had `"shape": [3]` (the number of _columns_ in the DataFrame) instead of `"shape": [4]` (the number of _rows_ in the DataFrame). 
This PR assumes that #1625 is in fact a bug, and that the shape values should not have an extra dimension added to them. If that assumption is incorrect, I would recommend also adding a disclaimer to this section like the one seen in the [Numpy Array section](https://mlserver.readthedocs.io/en/latest/user-guide/content-type.html#numpy-array) before it:
> ### Note
>By default, MLServer will …
=> Fix JSON input shapes

docs/examples/mlflow/README.md
Corrected the difference in column names in "MLflow Scoring Protocol" to match with the order in "Send test inference request". The values are in correct same order in both sections, so different columns are causing confusion.
=> Docs correction - Updated README.md in mlflow to match column names order

.github/workflows/tests.yml, Makefile, hack/generate-types.sh
Currently, since we don't exit on a command failure, it's been missed that generation is currently broken for the dataplane.
You can see an example in these logs from a previous workflow (https://github.com/SeldonIO/MLServer/actions/runs/8880776962/job/24381621013).
```
Writing mypy to dataplane_pb2.pyi
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/datamodel_code_generator/__main__.py", line 428, in main
generate(
File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/datamodel_code_generator/__init__.py", line 462, in generate
results = parser.parse()
File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/datamodel_code_generator/parser/base.py", line 1153, in parse
self.parse_raw() …
```
=> test: Detect generate failures

docs/examples/content-type/README.ipynb, docs/examples/content-type/README.md, docs/examples/custom/README.ipynb, docs/examples/custom/README.md, docs/getting-started/index.md, docs/user-guide/content-type.md, tests/repository/test_load.py, tests/rest/test_codecs.py
These were missed in https://github.com/SeldonIO/MLServer/pull/1748.
=> refactor(pydantic): Remaining migrations for deprecated functions

mlserver/types/dataplane.py, openapi/dataplane.yaml
This is a follow-up to #1752 and supersedes #1759.
It's understood that `string` type is no longer being treated as a list by Pydantic. `bytes` should be.
The code generator seems aware of the `bytes` type [1][2].
[1] https://github.com/koxudaxi/datamodel-code-generator/blob/fcab9a4d555d4b96d64bb277f974bb7507982fb2/datamodel_code_generator/types.py#L536-L569
[2] https://github.com/koxudaxi/datamodel-code-generator/blob/fcab9a4d555d4b96d64bb277f974bb7507982fb2/datamodel_code_generator/types.py#L624-L640
=> fix(pandas): Use Pydantic v2 compatible type

mlserver/codecs/pandas.py, runtimes/mlflow/mlserver_mlflow/metadata.py, runtimes/mlflow/tests/test_metadata.py, tests/codecs/test_pandas.py
Pandas codec currently breaks mlflow runtime's schema enforcement (#1625). This is because numeric mlflow datatypes are assigned `NumpyCodec` content type [by default](https://github.com/SeldonIO/MLServer/blob/410cf6f838782443267c88bd410cabf95c760c54/runtimes/mlflow/mlserver_mlflow/metadata.py#L24-L28), which decodes `PandasCodec`'s explicit batch size into a column vector:
```
input = RequestInput(
name="foo",
shape=[3, 1],
data=[1,2,3],
datatype="INT64",
)
NumpyCodec.decode_input(input)  # np.array([[1], [2], [3]])
```
However, `pd.Series` expects one-dimensional data, and when the `_decoded_payload` is converted to a `pd.Series` [here](https://github.com/SeldonIO/MLServer/blob/410cf6f838782443267c88bd410cabf95c760c54/mlserver/codecs/pandas.py#L28-L33) returns unexpected results:
``` …
```
=> Fix Pandas codec decoding from numpy arrays

.readthedocs.yaml, docs/Makefile, docs/conf.py
We don't support Python `3.8` anymore.
Poetry `1.8.1` matches what's currently in our Poetry lockfile.
Building the docs is currently failing [1], and this ideally will fix that.
[1] From readthedocs.org:
```
poetry install -vvv --without dev --with docs --with all-runtimes --with all-runtimes-dev
Loading configuration file /home/docs/.config/pypoetry/config.toml
The currently activated Python version 3.8.18 is not supported by the project (>=3.9,<3.12).
Trying to find and use a compatible version.
Trying python3
Trying python3.9
```
=> build: Bump versions for Read the Docs

docs/conf.py
For some reason, without this it's rendered as `"Contents"`. Doing this removes the quotes.
**Before**
**After**
=> docs: Remove quotes around local TOC

docs/user-guide/custom.md, mlserver/env.py, mlserver/parallel/pool.py, mlserver/parallel/registry.py, tests/cli/test_build_cases.py, tests/conftest.py, tests/parallel/conftest.py, tests/parallel/test_registry.py, tests/test_env.py, tests/testdata/environment.yml, tests/utils.py, tox.ini
As per #1461, MLServer currently spawns worker with the same Python version as the main process, so user-provided environment is forced to match the Python version of the server. However, `multiprocessing` allows setting the worker's executable path, this PR extends support for spawning workers in custom environments.
=> Spawn worker in custom environment

CONTRIBUTING.md, docs/PULL_REQUEST_TEMPLATE/pull_request_template.md
Basic improvements to CONTRIBUTING.md guide, besides a PR template for raising better/detailed PRs
- inside `/docs/` a pull request template folder, with a default PR template like this has been created.
- inside `CONTRIBUTING.md` doc, some best-effort ways to open/raise a PR, and install/develop along the main repo's `master` is suggested.
=> basic contributing guide on contributing and opening a PR

Dockerfile
This is to use the newest release of poetry 1.8.3. Actual lockfiles should be upgraded when they are changed in future PRs.
=> Build(deps): Update to poetry version 1.8.3 in docker build

docs/examples/index.md, docs/examples/streaming/README.ipynb, docs/examples/streaming/README.md, docs/examples/streaming/generate-request.json, docs/examples/streaming/model-settings.json, docs/examples/streaming/settings.json, docs/examples/streaming/text_model.py, docs/user-guide/index.md, docs/user-guide/streaming.md, mlserver/rest/openapi/dataplane.json, openapi/dataplane.yaml
This PR adds documentation for streaming. It includes:
-  a general user-guide for streaming
- a streaming example for a text model
=> Docs streaming

.github/workflows/release-sc.yml, .github/workflows/release.yml
Bumps `preflight` to 1.9.7 because the release action fails.
```
Error: could not submit to pyxis: could not create test results: status code: 400: body: {"type": "about:blank", "title": "Bad Request", "detail": "Validation error: 'github.com/redhat-openshift-ecosystem/openshift-preflight' version '1.4.2' is not supported. Supported versions are: ['1.9.2', '1.9.4', '1.9.5', '1.9.6', '1.9.7']", "status": 400, "trace_id": "0x8c282d1af616bcde76062a3af1c337c8"}
2024/06/07 12:02:17 could not submit to pyxis: could not create test results: status code: 400: body: {"type": "about:blank", "title": "Bad Request", "detail": "Validation error: 'github.com/redhat-openshift-ecosystem/openshift-preflight' version '1.4.2' is not supported. Supported versions are: ['1.9.2', '1.9.4', '1.9.5', '1.9.6', …
```
=> Bumped preflight version to 1.9.7

.github/workflows/licenses.yml
Adjusting reviewers to "SeldonIO/mlops"
=> fix: Update stale reviewer in licenses.yml workflow

docs/examples/streaming/README.ipynb, docs/examples/streaming/README.md, docs/examples/streaming/settings.json, docs/examples/streaming/text_model.py, docs/user-guide/streaming.md, mlserver/grpc/interceptors.py, mlserver/grpc/server.py, tests/grpc/test_interceptor.py, tests/testdata/settings-stream.json, tox.ini
This PR includes Prometheus interceptor support for gRPC streaming. Currently for gRPC streaming, we have to set `"metrics_endpoint": null`, thus Prometheus logs cannot be scraped.  It also updates docs and test for Prometheus interceptor.
=> Included Prometheus interceptor support for gRPC streaming

.github/workflows/tests.yml, runtimes/huggingface/poetry.lock, runtimes/huggingface/pyproject.toml
Limited `tensorflow`  upperbound to `2.17` for macos.
It seems that `2.17` is not compiled for `macos` (see package location [here](https://www.tensorflow.org/install/pip#package_location))
=> Fix tensorflow upperbound macos

.github/workflows/release-sc.yml, .github/workflows/release.yml
Bump `preflight` version to 1.10.0
=> ci: Merge change for release 1.6.1 [2]

poetry.lock, pyproject.toml
Adjusted the version range for FastAPI in pyproject.toml to "<0.116.0" to ensure compatibility with future releases. Updated the content hash in poetry.lock to reflect this change.
=> Update FastAPI version constraint

runtimes/mlflow/mlserver_mlflow/runtime.py, runtimes/mlflow/tests/test_runtime.py
Fixes SeldonIO/MLServer#1660
The parameters sent over REST to the mlserver are not forwarded to the predict function of the model. This PR fixes that issue.
Properly forward the params to the predict function of the model.
* #1660
-
-
=> Forward rest parameters to model

mlserver/parallel/registry.py
This PR adds an explicit cleanup for the custom environment when the pool is discarded. This is because in python 3.12 (for some reason) this is not called by default __del__ as with the previous python versions.
=> Force clean up env (for py 3.12)

runtimes/alibi-explain/poetry.lock
This is to fix a critical CVE https://security.snyk.io/vuln/SNYK-PYTHON-LIGHTGBM-8516056
=> Update lightgbm in alibi runtime to 4.6

mlserver/grpc/server.py
Resolves https://github.com/SeldonIO/MLServer/issues/2028
```
kwargs["interceptors"].insert(
AttributeError: 'tuple' object has no attribute 'insert'
```
---
Wasn't able to run `make test` locally, and install dependencies due to TF 2.18.0 no longer supported on intel x86, and `make test` failing out with a c++ compiler issue :/ 
Tested separately with
```
opentelemetry-instrumentation = "0.48b0"
opentelemetry-exporter-otlp-proto-grpc = "1.27.0"
```
and running
```
poetry run opentelemetry-instrument --metrics_exporter none --traces_exporter otlp mlserver start some-project/
```
which successfully works
=> Fix interceptors insert tuple -> list

mlserver/batching/adaptive.py
Before the fix, the timeout calculation subtracted the passed time from the timeout calculated for the previous round instead of subtracting it from the configured timeout value, causing time to pass quicker than expected.
Fixes #1936 
Fixes #2065
=> Fix AdaptiveBatcher timeout calculation

runtimes/mlflow/poetry.lock, runtimes/mlflow/pyproject.toml
See https://github.com/SeldonIO/MLServer/issues/2113
Tightened mlflow constraint in mlserver-mlflow to >=2.19.0 as otherwise an import in mlserver-mlflow fails (as it relies on something added in mlflow 2.19.0. See https://github.com/SeldonIO/MLServer/issues/2113 for further detail
n/a
n/a
n/a
=> Fix too loose mlflow dependency constraint in mlserver-mlflow
