Dockerfile

Fix(Dockerfile): delete useless copy

Fix(Dockerfile): delete useless copy

---

Makefile
mlserver/version.py
runtimes/lightgbm/mlserver_lightgbm/version.py
runtimes/mllib/mlserver_mllib/version.py
runtimes/sklearn/mlserver_sklearn/version.py
runtimes/xgboost/mlserver_xgboost/version.py

Fixes #99 
- Change build command so that it's relative to the source files

Fix build to include source

---

runtimes/sklearn/mlserver_sklearn/sklearn.py

Support other common file names for the SKLearn runtime

---

mlserver/parallel.py

Fixes #300 
- Use `spawn` instead of `fork` to avoid issues like https://github.com/tensorflow/tensorflow/issues/8220

Use spawn instead of fork for inference workers

---

docs/examples/lightgbm/README.md

remove extra blank lines

---

mlserver/rest/app.py
mlserver/settings.py
tests/testdata/settings.json

This PR will add configurable CORS middleware support on REST endpoints.
This references https://github.com/SeldonIO/MLServer/issues/386.

Add CORS support

---

mlserver/grpc/server.py
mlserver/rest/app.py
mlserver/settings.py
tests/metrics/conftest.py
tests/metrics/test_endpoint.py
tests/metrics/test_endpoint_cases.py
tests/metrics/utils.py

Make metrics endpoint configurable

---

runtimes/alibi-detect/mlserver_alibi_detect/runtime.py

Related to https://seldonio.atlassian.net/browse/DPL-865

Converting alibi detect drift runtime outputs to v2 payload

---

requirements/dev.txt

Workaround for the issue described in https://github.com/psf/black/issues/2964

Pin click on the dev deps to work around an issue with black

---

mlserver/registry.py

- Replace `asyncio.gather` for for-loop to ensure hooks are executed in the right order.

Fix issue with batching when parallel inference is enabled

---

docs/examples/huggingface/README.ipynb
docs/examples/huggingface/README.md
runtimes/huggingface/setup.py

Fixes part of #576 
Adds showcase of adaptive batching

Added showcase of adaptive batching for GPU parallelisation

---

mlserver/rest/app.py
tests/fixtures.py
tests/handlers/test_custom.py
tests/rest/test_custom.py
tests/rest/test_endpoints.py

Accept GZIP compression header

---

benchmarking/testserver/models/iris/model-settings.json
docs/user-guide/parallel-inference.md
mlserver/parallel/pool.py
mlserver/settings.py

Add deprecation note for parallel_workers at model settings level

---

mlserver/grpc/interceptors.py
mlserver/grpc/utils.py

Ensure support for grpcio 1.34.0

---

mlserver/repository.py

Fix for starting MLServer with relative paths

---

docs/user-guide/deployment/index.md

Points to seldon-core deployment currently.

Fix docs link to kserve deployment

---

.github/workflows/benchmark.yml
benchmarking/Makefile
benchmarking/README.md
benchmarking/common/grpc.js
benchmarking/scenarios/inference-grpc.js
benchmarking/scenarios/inference-rest.js
benchmarking/scenarios/inference.js
benchmarking/testserver/models/iris/model-settings.json
benchmarking/testserver/models/sum-model/model-settings.json
benchmarking/testserver/settings.json
mlserver/grpc/server.py
mlserver/rest/server.py
mlserver/server.py

- Split benchmarks into two separate ones to avoid some issues with k6
- Add GH Action to automate benchmarks on each PR with thresholds on throughput
- Update benchmarks' README results

Update benchmarks and add automation

---

runtimes/alibi-explain/mlserver_alibi_explain/explainers/black_box_runtime.py
runtimes/alibi-explain/mlserver_alibi_explain/runtime.py

Fix alibi explain runtime issues

---

.github/workflows/release.yml
requirements/dev.txt

Add GH Action to build MLServer images and packages

---

README.md

added link to huggingface to the doc

---

runtimes/mllib/README.md

llink in the hyperlink fixed

---

docs/examples/custom-json/README.ipynb
docs/examples/custom-json/README.md

solves #726
Not sure if needed but I didn't notice myself at the first pass of the notebook. Maybe happens for other users too.
Not sure if the changes are necessary but added for discussion anyway.

added code for extracting back text output

---

mlserver/types/__init__.py
mlserver/types/dataplane.py
mlserver/types/model_repository.py
openapi/dataplane.yaml
openapi/model_repository.yaml

Related to #331 
Updated some of the specs to align with the Seldon Core docs on the V2 API.

Update OpenAPI specs 

---

runtimes/huggingface/mlserver_huggingface/runtime.py

check for huggingface batch sizes

---

mlserver/grpc/server.py
mlserver/metrics/logging.py
mlserver/metrics/server.py
mlserver/rest/logging.py
mlserver/rest/server.py
mlserver/settings.py

Allow custom uvicorn and grpc configuration.
Closes #674

Add custom server settings

---

mlserver/logging.py
mlserver/settings.py
requirements/dev.txt

Resolves https://github.com/SeldonIO/MLServer/issues/741

Add support for dictConfig with json file

---

runtimes/huggingface/mlserver_huggingface/runtime.py

added support for huggingface runtime speech models

---

mlserver/kafka/server.py

I tried #777 and had same problem. my suggested solution to this issue is in this PR.
Maybe fixes: #777

Fix async consuming requests

---

mlserver/grpc/converters.py
tests/grpc/test_converters.py

Implemented a few missing gRPC converters

---

Dockerfile
requirements/docker.txt

Fixes #789 
- Change base image to `ubi9/ubi-minimal`
- Remove `mlops-tempo` from base image
- Add Conda to base image

Move base image to UBI9

---

Dockerfile

Closes https://github.com/SeldonIO/MLServer/issues/820

add license to /licenses

---

mlserver/rest/logging.py
mlserver/rest/server.py

Disable health access logs if debug is disabled

---

mlserver/rest/server.py

Implemented exactly like the gRPC message.

feat(rest): log HTTP server listening event

---

mlserver/grpc/utils.py

Log plain exceptions in gRPC error handler

---

runtimes/alibi-explain/mlserver_alibi_explain/common.py
runtimes/alibi-explain/requirements/dev.txt
runtimes/alibi-explain/tests/conftest.py
runtimes/alibi-explain/tests/test_common.py
setup.cfg

Send "don't log" header for Alibi's internal requests

---

mlserver/model.py
mlserver/parallel/worker.py
mlserver/registry.py
mlserver/settings.py
tests/test_registry.py

Fixes #869 
- Remove models which failed to load from registry
- Refactor a couple things on the registry

Remove models which failed to load

---

mlserver/metrics/server.py

Ensure metrics server respects logging config

---

docs/conf.py
docs/reference/api/codecs.md
docs/reference/api/index.md
docs/reference/api/model.md
docs/reference/api/types.md
docs/reference/index.md
docs/user-guide/content-type.md
docs/user-guide/custom.md
mlserver/codecs/__init__.py
mlserver/codecs/base.py
mlserver/codecs/datetime.py
mlserver/codecs/numpy.py
mlserver/codecs/pandas.py
mlserver/codecs/string.py
mlserver/model.py

Add initial docs around main classes of MLServer's Python API

Document main Python API

---

docs/user-guide/adaptive-batching.md

reflecting the changes of https://github.com/SeldonIO/MLServer/pull/925 and https://github.com/SeldonIO/MLServer/pull/916 to documentation as discussed in https://github.com/SeldonIO/MLServer/pull/916#issuecomment-1378478732

added merging and spliting params to doc

---

.github/workflows/security.yml

Snyk has issues working with complex setup.py files (e.g. https://github.com/snyk/cli/issues/1367).
To account for this, we set up the environment and then dump it with `pip freeze` into a `requirements.txt`. Note that this environment will include both production and development dependencies.
Once we move into Poetry (#139 ), this workaround can be replaced for the lock file.

Update security pipeline

---

runtimes/huggingface/mlserver_huggingface/common.py
runtimes/huggingface/mlserver_huggingface/runtime.py
runtimes/huggingface/setup.py

- Support Optimum's new imports
- Add upper boundary for Optimum to avoid breaking changes

Add compatibility for Optimum 1.7

---

docs/user-guide/custom.md

Improve custom Docker image docs

---

docs/user-guide/content-type.md

Add docs around converting to / from JSON

---

runtimes/sklearn/README.md

Document SKLearn available outputs

---

runtimes/xgboost/README.md
runtimes/xgboost/mlserver_xgboost/xgboost.py
runtimes/xgboost/tests/conftest.py
runtimes/xgboost/tests/test_xgboost.py

Add support for `.ubj` models and improve XGBoost docs

---

setup.py

Add OS classifiers to project's metadata

---

requirements/docker.txt
runtimes/alibi-detect/requirements/dev.txt

Reverts SeldonIO/MLServer#1164

Revert "Add workaround for typing-extensions issue"

---

.github/workflows/tests.yml

MacOS tests keep failing randomly with `ConnectionResetError`. Changing Colima's network driver may help according to https://github.com/abiosoft/colima/issues/577.

Use Slirp as Colima's network driver in MacOS tests

---

runtimes/alibi-detect/mlserver_alibi_detect/runtime.py
runtimes/alibi-detect/tests/conftest.py
runtimes/alibi-detect/tests/test_drift_detector.py

added drift metrics to be scraped by prometheus

Publish is_drift metric to Prom

---

.github/workflows/release.yml
.github/workflows/tests.yml
Makefile

- Update `release` pipeline to use Poetry for building and publish Python packages
- Update `test` pipeline to only run step to maximise space in Linux

Update release CI to use Poetry

---

.github/dependabot.yml

Reflect the appropriate reviewers as per the organisation.

build(dependabot): Change reviewers

---

mlserver/parallel/dispatcher.py

This is a regression from presumably the line being split up.

fix: Missing f-string directives

---

.github/workflows/tests.yml
Makefile
hack/generate-types.sh

This makes it easier to know which types generation is failing. It's a follow-on from https://github.com/SeldonIO/MLServer/pull/1729.

build: Add granularity in types generation

---

docs/conf.py
mlserver/version.py
pyproject.toml
runtimes/alibi-detect/mlserver_alibi_detect/version.py
runtimes/alibi-detect/pyproject.toml
runtimes/alibi-explain/mlserver_alibi_explain/version.py
runtimes/alibi-explain/pyproject.toml
runtimes/catboost/mlserver_catboost/version.py
runtimes/catboost/pyproject.toml
runtimes/huggingface/mlserver_huggingface/version.py
runtimes/huggingface/pyproject.toml
runtimes/lightgbm/mlserver_lightgbm/version.py
runtimes/lightgbm/pyproject.toml
runtimes/mlflow/mlserver_mlflow/version.py
runtimes/mlflow/pyproject.toml
runtimes/mllib/mlserver_mllib/version.py
runtimes/mllib/pyproject.toml
runtimes/sklearn/mlserver_sklearn/version.py
runtimes/sklearn/pyproject.toml
runtimes/xgboost/mlserver_xgboost/version.py
runtimes/xgboost/pyproject.toml

This PR changes the version to the 1.6.0.dev2.

Bumped to 1.6.0.dev2

---

.github/workflows/tests.yml
runtimes/huggingface/poetry.lock
runtimes/huggingface/pyproject.toml

This PR fixes `macos - huggingface` CI. `torch` no longer supports `macos x86` (see issue [here](https://github.com/pytorch/pytorch/issues/114602))

Fix CI/CD macos-huggingface

---

.github/workflows/tests.yml
poetry.lock
pyproject.toml
runtimes/alibi-detect/poetry.lock
runtimes/alibi-explain/poetry.lock
runtimes/catboost/poetry.lock
runtimes/huggingface/poetry.lock
runtimes/lightgbm/poetry.lock
runtimes/mlflow/poetry.lock
runtimes/mllib/poetry.lock
runtimes/sklearn/poetry.lock
runtimes/xgboost/poetry.lock

Fixes: https://github.com/SeldonIO/MLServer/issues/1806

Update poetry lock

---

.github/workflows/release.yml

This PR adds `catboost` runtime to the release workflow.
Fixes: https://github.com/SeldonIO/MLServer/issues/1838

Update release.yml to include catboost

---

tox.ini

This PR modifies the test config to run the gRPC test serially.

Run gRPC test serially

---

mlserver/codecs/pandas.py
tests/codecs/test_pandas.py

This PR fixes the byte encoding issue in the PandasCodec. Addresses #2112.

Fixed byte encoding in the PandasCodec
